#!/bin/sh
wal -R
sxhkd &

bspc monitor -d 一 二 三 四 五 六 七 八 九 十
#bspc monitor -d 1 2 3 4 5 6 7 8 9 10

. "${HOME}/.cache/wal/colors.sh"

bspc config border_width           4
bspc config window_gap             0

#bspc config top_padding            $(( 12 + 27+8 + 13  +  35 ))
#bspc config left_padding           $(( 30  +  105 ))
#bspc config right_padding          $(( 30  +  105 ))
#bspc config bottom_padding         $(( 20  +  35 ))

#bspc config top_padding            $(( 12 + 27+8 + 13  +  35+15))
#bspc config left_padding           $(( 30  +  105+45 ))
#bspc config right_padding          $(( 30  +  105+45 ))
#bspc config bottom_padding         $(( 20  +  35+15 ))

xsetroot -cursor_name left_ptr

bspc config split_ratio            0.5
bspc config borderless_monocle     false
bspc config gapless_monocle        false

bspc config focus_follows_pointer  true
#bspc config click_to_focus any

bspc config normal_border_color    "$color1"
bspc config active_border_color    "$color7"
bspc config focused_border_color   "$color4"
bspc config presel_border_color    "$color1"

bspc rule -a URxvt:URxvtFloat state=floating
bspc rule -a URxvt:URxvt-dmesg desktop='^10'
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^1'
bspc rule -a mplayer2 state=floating
bspc rule -a mpv state=floating
bspc rule -a imv state=floating
bspc rule -a Spicy state=floating
bspc rule -a qemu-system-x86_64 state=floating
bspc rule -a feh:feh state=floating
bspc rule -a feh:fehwrap-fs state=fullscreen

# Autorun stuff
$HOME/.config/polybar/launch.sh
urxvtc -name URxvt-dmesg -e dmesg -w
